### ISSUE TITLE
New maintainer: 

### ISSUE THREAD

**Issue by zosrothko** [javacc/javaccPlugin#49]
Hi John

The JavaCC org has already a set of tools for managing JavaCC (including a fork of your plugin) at [https://github.com/javacc](https://github.com/javacc). Thus, one are willling to take in charge the maintenance of your plugin and it would make sense to concentrate all JavaCC side tools in this JavaCC organization. IMHO, the best way is to transfer the ownership if you don't mind.

Rgds

**Comment by johnmartel** [comment]
Hi @zosrothko,

I am currently on the last week before leaving for vacation, so I'm a little busy this week. I will get back to you early next week to sort this out and transfer the ownership in a seamless manner if possible. I do have a few things to verify/fix like access to the Gradle plugin repository, maven central and jcenter. Hopefully, this should be simple enough.

**Comment by zosrothko** [comment]
Thanks for your effort in sharing your work.

**Comment by johnmartel** [comment]
@zosrothko I invited you as a collaborator to this repository so that you can initiate the transfer to your organization. To transfer a repository to an organization, one needs to have permission to create repositories in that organization: https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#repository-transfers-and-organizations

For the Gradle plugins portal, you will need to contact Gradle support once the repo transfer is complete: https://plugins.gradle.org/docs/reclaiming

For Maven Central and Bintray/jcenter, I think the best course of action is to create your own organizational account (if you don't already have one) and publish the new versions there (and document that change in README.md). This way, builds using the old versions I already published won't be broken.

**Comment by zosrothko** [comment]
Hi John... I accepted your invitation but I do not get the "settings" tab on my javaccPlugin. From my understanding, the `Collaborator` role is not enough. Could you check. Thx

![image](https://user-images.githubusercontent.com/7262593/89188173-920b8900-d59e-11ea-80e0-7476ed3292e2.png)

**Comment by johnmartel** [comment]
@zosrothko You should now be good to go. I had to move the repository from my user account to my organization to be able to grant admin permissions to an outside collaborator.

**Comment by zosrothko** [comment]
@johnmartel Transfer to organization `https://github.com/javacc` done. Thanks for your donation. You will be referenced in the documentation.

**Comment by johnmartel** [comment]
Thanks for taking command and contributing to the community!

**Comment by zbynek** [comment]
@johnmartel I guess this issue can be closed now?

**Comment by johnmartel** [comment]
@zbynek Yes!
