### ISSUE TITLE
Repository documentation outdated

### ISSUE THREAD

**Issue by ryanramsdell27** [javacc/javaccPlugin#69]
The readme links to an outdated version https://plugins.gradle.org/plugin/ca.coglinc.javacc,  possibly should be https://plugins.gradle.org/plugin/org.javacc.javacc instead

It may also be helpful to have information about including the `gradlePluginPortal()` as part of the plugin management repositories --- although this may have just been a result of my own confusion switching from maven to gradle

**Comment by zbynek** [comment]
Thanks, link fixed in https://github.com/javacc/javaccPlugin/commit/a8bd8be23302ec51b1f884c5c8469172872e4179

For the latter: plugins are [resolved from the plugin portal by default](https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories), so you should only explicitly add `gradlePluginPortal` if you want to get plugins from multiple repositories. I think in general the description of the plugin management should stay in Gradle documentation and not be duplicated by individual plugins. 

If you have any suggestions for improving documentation specific to this plugin, you're welcome to create a pull request in this repository.
